language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install libssl-dev libssl0.9.8 libssl1.0.0 libdnet-dev libsmi2-dev
  - cat /usr/include/x86_64-linux-gnu/bits/stdio2.h

script:
  - echo DONE
